-- Add value proposition and career fields to employees table
-- These fields are required for the Career Block in employee profiles
-- Note: target_role already exists in schema.sql, but we add it here for safety

-- Add current_role column if it doesn't exist
-- Note: In schema.sql, 'role' field exists, but we need 'current_role' for career progression
ALTER TABLE employees 
ADD COLUMN IF NOT EXISTS current_role VARCHAR(255);

-- target_role already exists in schema.sql, but ensure it's there
-- ALTER TABLE employees ADD COLUMN IF NOT EXISTS target_role VARCHAR(255);

-- Add value_proposition column if it doesn't exist
ALTER TABLE employees 
ADD COLUMN IF NOT EXISTS value_proposition TEXT;

-- Add comment to explain these fields
COMMENT ON COLUMN employees.current_role IS 'Current role of the employee in the company (filled during company registration)';
COMMENT ON COLUMN employees.target_role IS 'Target role for career progression (filled during company registration)';
COMMENT ON COLUMN employees.value_proposition IS 'AI-generated value proposition based on current_role and target_role (generated by Gemini)';

